language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

os:
  - linux

install:
  - pip install -e .
  - pip install pytest pytest-cov

script:
  - pytest --cov=geeknote --cov-report=xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -t c267916c-f35b-4fb2-b27d-aae28242e43e

notifications:
  email: false
