version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install package and dependencies
          command: |
            pip install -e .
            pip install pytest pytest-cov
      - run:
          name: Run tests with coverage
          command: pytest --cov=geeknote --cov-report=xml
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t c267916c-f35b-4fb2-b27d-aae28242e43e

workflows:
  test-workflow:
    jobs:
      - test
